In [1]:
import pandas as pd

In [12]:
df = pd.read_csv(r'/Users/arnenyeck/Desktop/MSU/CIS 518- Foundation of data science/project_2/owid-covid-data.csv')
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2/24/20,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2/25/20,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2/26/20,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2/27/20,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2/28/20,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168159,ZWE,Africa,Zimbabwe,3/9/22,240343.0,0.0,405.714,5400.0,0.0,0.571,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
168160,ZWE,Africa,Zimbabwe,3/10/22,241548.0,1205.0,577.857,5408.0,8.0,1.714,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
168161,ZWE,Africa,Zimbabwe,3/11/22,241548.0,0.0,401.286,5408.0,0.0,1.571,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
168162,ZWE,Africa,Zimbabwe,3/12/22,242069.0,521.0,435.714,5412.0,4.0,2.143,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
168163,ZWE,Africa,Zimbabwe,3/13/22,242515.0,446.0,472.286,5414.0,2.0,2.143,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [13]:
df.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168164 entries, 0 to 168163
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    168164 non-null  object
 1   continent                                   158104 non-null  object
 2   location                                    168164 non-null  object
 3   date                                        168164 non-null  object
 4   total_cases                                 165117 non-null  float64
 5   new_cases                                   164920 non-null  float64
 6   new_cases_smoothed                          162930 non-null  float64
 7   total_deaths                                147205 non-null  float64
 8   new_deaths                                  147212 non-null  float64
 9   new_deaths_smoothed                         145098 non-null  float64
 10  total_cases_per_million                     164351 non-null  float64
 11  new_cases_per_million                       164154 non-null  float64
 12  new_cases_smoothed_per_million              162170 non-null  float64
 13  total_deaths_per_million                    146452 non-null  float64
 14  new_deaths_per_million                      146459 non-null  float64
 15  new_deaths_smoothed_per_million             144351 non-null  float64
 16  reproduction_rate                           127352 non-null  float64
 17  icu_patients                                23727 non-null   float64
 18  icu_patients_per_million                    23727 non-null   float64
 19  hosp_patients                               24884 non-null   float64
 20  hosp_patients_per_million                   24884 non-null   float64
 21  weekly_icu_admissions                       5522 non-null    float64
 22  weekly_icu_admissions_per_million           5522 non-null    float64
 23  weekly_hosp_admissions                      11051 non-null   float64
 24  weekly_hosp_admissions_per_million          11051 non-null   float64
 25  total_tests                                 70123 non-null   float64
 26  new_tests                                   68036 non-null   float64
 27  total_tests_per_thousand                    70123 non-null   float64
 28  new_tests_per_thousand                      68036 non-null   float64
 29  new_tests_smoothed                          85462 non-null   float64
 30  new_tests_smoothed_per_thousand             85462 non-null   float64
 31  positive_rate                               80069 non-null   float64
 32  tests_per_case                              79472 non-null   float64
 33  tests_units                                 87877 non-null   object
 34  total_vaccinations                          45739 non-null   float64
 35  people_vaccinated                           43506 non-null   float64
 36  people_fully_vaccinated                     40782 non-null   float64
 37  total_boosters                              18097 non-null   float64
 38  new_vaccinations                            37790 non-null   float64
 39  new_vaccinations_smoothed                   86203 non-null   float64
 40  total_vaccinations_per_hundred              45739 non-null   float64
 41  people_vaccinated_per_hundred               43506 non-null   float64
 42  people_fully_vaccinated_per_hundred         40782 non-null   float64
 43  total_boosters_per_hundred                  18097 non-null   float64
 44  new_vaccinations_smoothed_per_million       86203 non-null   float64
 45  new_people_vaccinated_smoothed              84938 non-null   float64
 46  new_people_vaccinated_smoothed_per_hundred  84938 non-null   float64
 47  stringency_index                            131278 non-null  float64
 48  population                                  167081 non-null  float64
 49  population_density                          149560 non-null  float64
 50  median_age                                  139351 non-null  float64
 51  aged_65_older                               137841 non-null  float64
 52  aged_70_older                               138604 non-null  float64
 53  gdp_per_capita                              140032 non-null  float64
 54  extreme_poverty                             92215 non-null   float64
 55  cardiovasc_death_rate                       138290 non-null  float64
 56  diabetes_prevalence                         145541 non-null  float64
 57  female_smokers                              107218 non-null  float64
 58  male_smokers                                105747 non-null  float64
 59  handwashing_facilities                      69329 non-null   float64
 60  hospital_beds_per_thousand                  125024 non-null  float64
 61  life_expectancy                             156988 non-null  float64
 62  human_development_index                     137765 non-null  float64
 63  excess_mortality_cumulative_absolute        5747 non-null    float64
 64  excess_mortality_cumulative                 5747 non-null    float64
 65  excess_mortality                            5747 non-null    float64
 66  excess_mortality_cumulative_per_million     5747 non-null    float64
dtypes: float64(62), object(5)
memory usage: 86.0+ MB

In [ ]:
user_string = input()
def remove_digits(user_string):
    user_string = input()
    tempArr = []
    for i in user_string:
        if i.isalpha():
            tempArr.append(i)
        else:
            pass
    print(''.join(tempArr))
remove_digits(user_string )